TorchSim/torch-sim

.github/workflows/test.yml
tests/models/test_fairchem.py
torch_sim/models/fairchem.py
torch_sim/models/graphpes.py
torch_sim/models/lennard_jones.py
torch_sim/models/mace.py
torch_sim/models/mattersim.py
torch_sim/models/morse.py
torch_sim/models/orb.py
torch_sim/models/sevennet.py
torch_sim/unbatched/models/lennard_jones.py
torch_sim/unbatched/models/mace.py
torch_sim/unbatched/models/morse.py
torch_sim/unbatched/models/particle_life.py
torch_sim/unbatched/models/soft_sphere.py

Will include tests with OMat models as in [quacc](https://github.com/Quantum-Accelerators/quacc) in the next PR.

FairChemModel Updates: PBC handling, test on OMat24 pre-trained model

---

tests/conftest.py
tests/test_integrators.py
torch_sim/integrators.py
torch_sim/models/sevennet.py
torch_sim/runners.py

Include a summary of major changes in bullet points:
Work-in-progress pull requests are encouraged, but please enable the draft status on your PR.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use the pre-commit hook provided in the repository. Simply run
`pre-commit install` and a check will be run prior to allowing commits.

Support different temperatures in batches

---

.github/workflows/test.yml

Avoid HF unless in fairchem tests, GraphPES failed on main for issues related to HF

Only install HF for fairchem tests

---

README.md
docs/reference/index.rst
examples/scripts/4_High_level_api/4.2_auto_batching_api.py
examples/scripts/5_Workflow/5.3_In_Flight_WBM.py
examples/tutorials/autobatching_tutorial.py
tests/Interactive-1.interactive
tests/models/test_graphpes.py
tests/test_autobatching.py
tests/test_runners.py
torch_sim/__init__.py
torch_sim/autobatching.py
torch_sim/runners.py

Work-in-progress pull requests are encouraged, but please enable the draft status on your PR.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use the pre-commit hook provided in the repository. Simply run
`pre-commit install` and a check will be run prior to allowing commits.

Reduce test flakiness and hotfix docs

---

tests/test_integrators.py
tests/test_neighbors.py
tests/test_state.py
torch_sim/integrators.py
torch_sim/models/interface.py
torch_sim/properties/correlations.py
torch_sim/state.py
torch_sim/trajectory.py
torch_sim/unbatched/unbatched_integrators.py

* I found that the `npt_langevin` integrator appears to be broken in #152 
* I think this is arising because the kinetic energy term currently being used is per-atom, whereas it needs to be per-structure
* this fix now allows `npt_langevin` to reproduce the expected volume of a perfect-gas:
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use the pre-commit hook provided in the repository. Simply run
`pre-commit install` and a check will be run prior to allowing commits.

fix `npt_langevin`

---

examples/tutorials/metatensor_tutorial.py
pyproject.toml
torch_sim/models/metatensor.py

Fix #155
I don't have access to a CUDA GPU, so I would appreciate either @frostedoyster or @orionarcher checking that this does work in practice! 
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use the pre-commit hook provided in the repository. Simply run
`pre-commit install` and a check will be run prior to allowing commits.

Make sure to move data to CPU before calling vesin

---

tests/test_io.py
torch_sim/integrators.py
torch_sim/optimizers.py
torch_sim/unbatched/unbatched_optimizers.py

Fix virial calculations in `optimizers` and `integrators`

---

torch_sim/models/orb.py

Makes Orb's `state_to_atoms_graph` calculation slightly more efficient with a single loop across the batch by reverting from `batch_compute_pbc_radius_graph` which internally was already looping across the batch.

Improves Orb's state_to_atoms_graph calculation

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
tests/models/test_mace.py
tests/test_autobatching.py
torch_sim/autobatching.py
torch_sim/runners.py

Pads max memory estimation by 0.9 to prevent running out of memory due to memory fluctuations. Probable fix for issue #159.

Pad memory estimation

---

tests/test_runners.py
torch_sim/autobatching.py
torch_sim/runners.py

Throw error if autobatcher type is wrong.

throw error if autobatcher type is wrong

---

torch_sim/models/sevennet.py

Include a summary of major changes in bullet points:
* Fix 1: `torch.dtype == torch.float32`  to  `dtype == torch.float32`
* Change 1: raise ValueError if `type_map` is None. The switch is introduced due to historical reason and should be True.

Refactor sevennet model

---

.github/workflows/docs.yml
pyproject.toml

Avoid needing to use compat mode when installing to get pylance features. Note this is deprecated.

Try out hatchling for build vs setuptools

---

pyproject.toml
tests/test_io.py
tests/test_trajectory.py
torch_sim/io.py
torch_sim/trajectory.py

* Moved the ase dependency out of the optional [test] dependency to a required dependency because it doesn't seem like a test. Here is an example of it being used in the trajectory file https://github.com/Radical-AI/torch-sim/blob/main/torch_sim/trajectory.py#L866

io Optional Dependencies in pyproject.toml

---

tests/conftest.py
tests/models/conftest.py
tests/test_integrators.py
tests/test_transforms.py
torch_sim/integrators.py
torch_sim/transforms.py
torch_sim/unbatched/unbatched_integrators.py

The tests of the function do not use the row vector cell so this suggests this is a bug that it's used in the integrators.
see that tests of function don't use the swap axis: https://github.com/Radical-AI/torch-sim/blob/d2cee6628ff3b4a8da7557772cc12a669a0c09b4/tests/test_transforms.py#L267

Updates integrator logic per #171. 

---

.github/workflows/link-check.yml
.pre-commit-config.yaml
examples/scripts/7_Others/7.3_Batched_neighbor_list.py
examples/scripts/readme.md
examples/tutorials/using_graphpes_tutorial.py
tests/models/test_fairchem.py
tests/test_neighbors.py
tests/test_runners.py
torch_sim/integrators.py
torch_sim/math.py
torch_sim/models/interface.py
torch_sim/models/lennard_jones.py
torch_sim/models/mace.py
torch_sim/models/mattersim.py
torch_sim/models/metatensor.py
torch_sim/models/morse.py
torch_sim/models/orb.py
torch_sim/models/sevennet.py
torch_sim/models/soft_sphere.py
torch_sim/neighbors.py
torch_sim/state.py
torch_sim/trajectory.py
torch_sim/transforms.py
torch_sim/unbatched/models/lennard_jones.py
torch_sim/unbatched/models/morse.py
torch_sim/unbatched/models/particle_life.py
torch_sim/unbatched/models/soft_sphere.py
torch_sim/unbatched/unbatched_integrators.py
torch_sim/workflows/a2c.py

also faster since `lychee` is in `rust`

stricter dead link checks: swap `markdown-link-check` for `lychee`

---

tests/conftest.py
tests/test_optimizers_vs_ase.py
torch_sim/optimizers.py

closes #198 
* `torch_sim/optimizers.py` had a bug discovered by @t-reents in FIRE relaxation where atomic positions were not correctly updated when the cell changed. resolved by scaling atomic positions by the difference between new and previous cell after each cell update
* new relaxation tests for `OsN2` and distorted `FCC Al` structures in `test_optimizers_vs_ase.py`, covering both Frechet and Unit Cell FIRE optimizers
* tightened existing assertion tolerances in `test_optimizers_vs_ase.py` due to improved agreement between `torch-sim` and `ASE` optimizers
in a future PR, it probably makes sense to change the handling of atom positions from absolute to fractional (unwrapped) coordinates which would mean the atom positions don't require manual scaling after cell changes

Fix unit and frechet cell FIRE optimizers not rescaling atom positions after each cell update

---

examples/scripts/7_Others/7.6_Compare_ASE_to_VV_FIRE.py
examples/tutorials/low_level_tutorial.py
tests/models/test_graphpes.py
torch_sim/models/sevennet.py
torch_sim/optimizers.py
torch_sim/properties/correlations.py

I updated the 7.6 Script in examples to test both the FrechetCellFilter in torch-sim and ASE. It generates plots for each of the 5 structures in the batch. Through this I have identified that ASE consistently converges in fewer steps for every case, even when I adopt the ase_fire `md_flavor`. 
The script tests 6 structures of (3,2,2) supercells:
1. Pure Silicon atoms: 96
2. Pure Copper atoms: 36
3. Pure Iron atoms: 36
4. Pure Silicon with 1 vacancy: 95 atoms
5. Pure Copper with 1 vacancy: 35 atoms
6. Pure Iron with 1 vacancy: 35 atoms
Here is the comparison of convergence steps needed for each of the 6 structures:
Here are the average displacements for each structure compared to ASE:
Here are the final energies compared to their ASE Basecase:
Seems like there is an issue here?

Difference in ASE FrechetCellFilter vs Torch-Sim (both md_flavors) + enhanced convergence testing

---

.github/workflows/link-check.yml
examples/scripts/7_Others/7.6_Compare_ASE_to_VV_FIRE.py
tests/test_optimizers_vs_ase.py
tests/test_runners.py
torch_sim/autobatching.py
torch_sim/math.py
torch_sim/optimizers.py
torch_sim/runners.py

It seems that the remaining deviations could be fixed. This branch is already based on the changes in #201, I'll do the rebase once it is merged.
* I reduced the number of "inner" updates in the testing script to `1`, in order to get the precise number of convergence steps
* In the pos-only case, two small fixes were necessary that led to a wrong (or better to say different) `dt`
* The Frechet Cell optimization also required some additional changes, i.e., correctly scaling the positions with respect to the deformation gradient. See https://gitlab.com/ase/ase/-/blob/master/ase/filters.py?ref_type=heads#L440-441 and https://gitlab.com/ase/ase/-/blob/master/ase/filters.py?ref_type=heads#L405-406
* The previously (#199) introduced rescaling of the positions with respect to the new cell was …

Fix discrepancies between `FIRE` optimisations in `ASE` and `torch-sim` 

---

torch_sim/models/orb.py

OrbModel wrapper returns a dim-0 tensor for energy for a input containing a single system, because of a squeeze() in orb.py line 419. This is not the behaviour of other models like SevenNet. This causes ts.integrate to fail when trying to split the system.
```
from ase.build import bulk
from torch_sim.models.orb import OrbModel
from torch_sim.state import initialize_state
from orb_models.forcefield import pretrained
import torch
import os
import torch_sim as ts
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
orbff = pretrained.orb_v3_conservative_inf_omat(
device=device,
precision="float32-highest",
compile=False
)
orb_model = OrbModel(model=orbff, dtype=torch.get_default_dtype())
from torch_sim.integrators.nvt import nvt_langevin
n_steps = 30
timestep = 0.001 …
```

fix:orb squeeze provides incorrect shape for energy tensor

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dco.yml
CONTRIBUTING.md

* Switch the repo from requiring a CLA to a new Contributor's Certification clause in [CONTRIBUTING.md](CONTRIBUTING.md) that users must agree to in PRs.
We highly recommended installing the pre-commit hooks running in CI locally to speedup the development process. Simply run `pip install pre-commit && pre-commit install` to install the hooks which will check your code before each commit.

Remove Contributor License Agreement (CLA) in favor of certification in contributing.md
